title: Learning Agents
description: > # this means to ignore newlines until "baseurl:"
  강화학습 논문 리뷰 스터디 발표 자료 저장소
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://learning-agents-kr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Learning Agents # add your name
author-img: Graident_Ai_Robot.jpg # add your photo
about-author: 강화학습 논문 리뷰 스터디 자료 저장소 # add description

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
# Conversion 
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
